name: 'Display message'
description: Display message from user
inputs:
  message:
    description: 'Input message'
    required: true
    default: 'hi'
runs:
  using: 'docker'
  image: '../../../Dockerfile'
