on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Input message'
        required: true

name: 'Learn Github Actions - Message'
jobs:
  test:
    name: Display Message
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Checkout Publish Repo
        uses: actions/checkout@v2

      - name: Display Message
        uses: ./.github/actions/display_message
        with:
          message: ${{ github.event.inputs.message }}